version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: uberpl_db
      POSTGRES_USER: hugh
      POSTGRES_PASSWORD: december90
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hugh"]
      interval: 10s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://uberpl_user:yourpassword@postgres:5432/uberpl_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      ENCRYPTION_PASSWORD: your-encryption-password

volumes:
  postgres_data: